name: CI/CD diplom-app

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Application Code
      uses: actions/checkout@v4

    - name: Install Yandex Cloud CLI
      run: |
        curl -sSL https://yandexcloud.net | bash -s -- -i /usr/local/yandex-cloud -b /usr/local/bin -n

    - name: Log in to Yandex Container Registry
      run: echo "${{ secrets.YC_TOKEN }}" | docker login --username oauth --password-stdin cr.yandex
    
    - name: Build and Push Docker Image (Flat Syntax)
      run: |
        CLEAN_REGISTRY_ID=$(echo "${{ secrets.YC_REGISTRY_ID }}" | tr -d '\r' | tr -d '\n' | tr -d ' ')
        REF_NAME=$(echo "${{ github.ref_name }}" | tr -d '\r' | tr -d '\n' | tr -d ' ')
        
        "/usr/bin/docker" buildx build --platform linux/amd64 --output type=image,push=true -t "cr.yandex/${CLEAN_REGISTRY_ID}/diplom-app:latest" -t "cr.yandex/${CLEAN_REGISTRY_ID}/diplom-app:${REF_NAME}" .

    - name: Deploy to Kubernetes Cluster
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        YC_TOKEN: ${{ secrets.YC_TOKEN }}
        YC_CLUSTER_ID: ${{ secrets.YC_CLUSTER_ID }} # Добавьте ID кластера в секреты GitHub
      run: |
        RUNNER_PUBLIC_IP=$(curl -s https://ifconfig.me)
        echo "IP-адрес раннера деплоя: $RUNNER_PUBLIC_IP"
        mkdir -p ~/.kube
        yc managed-kubernetes cluster get-credentials --id "$YC_CLUSTER_ID" --external --force --token "$YC_TOKEN" --kubeconfig "$HOME/.kube/config"

        REF_NAME="${GITHUB_REF#refs/tags/}"
        CLEAN_REG_ID=$(echo "${{ secrets.YC_REGISTRY_ID }}" | tr -d '\r' | tr -d '\n' | tr -d ' ')
        
        kubectl patch deployment diplom-app \
          --namespace=default \
          --type='json' \
          -p="[{\"op\": \"replace\", \"path\": \"/spec/template/spec/containers/0/image\", \"value\": \"cr.yandex/${CLEAN_REG_ID}/diplom-app:${REF_NAME}\"}]"

        kubectl rollout restart deployment/diplom-app --namespace=default
