name: CI/CD diplom-app

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Application Code
      uses: actions/checkout@v4

    - name: Log in to Yandex Container Registry
      run: echo "${{ secrets.YC_TOKEN }}" | docker login --username oauth --password-stdin cr.yandex
    
    - name: Build and Push Docker Image (Flat Syntax)
      run: |
        CLEAN_REGISTRY_ID=$(echo "${{ secrets.YC_REGISTRY_ID }}" | tr -d '\r' | tr -d '\n' | tr -d ' ')
        REF_NAME=$(echo "${{ github.ref_name }}" | tr -d '\r' | tr -d '\n' | tr -d ' ')
        
        "/usr/bin/docker" buildx build --platform linux/amd64 --output type=image,push=true -t "cr.yandex/${CLEAN_REGISTRY_ID}/diplom-app:latest" -t "cr.yandex/${CLEAN_REGISTRY_ID}/diplom-app:${REF_NAME}" .

    - name: Deploy to Kubernetes Cluster
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        YC_TOKEN: ${{ secrets.YC_TOKEN }}
        YC_CLUSTER_ID: ${{ secrets.YC_CLUSTER_ID }}
        YC_SECURITY_GROUP_ID: ${{ secrets.YC_SECURITY_GROUP_ID }}
      run: |
        curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -n
        export PATH="$HOME/yandex-cloud/bin:$PATH"

        CLEAN_SG_ID="enptdv68dlmjkj0nr0mc"


        RUNNER_PUBLIC_IP=$(curl -s https://ifconfig.me)
        echo "IP-адрес раннера деплоя: $RUNNER_PUBLIC_IP"

        mkdir -p ~/.kube
        yc config set token "$YC_TOKEN"

        echo "=== Открываем доступ для IP $RUNNER_PUBLIC_IP в Security Group ==="
        yc vpc security-group update-rules "$CLEAN_SG_ID" \
          --add-rule "direction=ingress,protocol=tcp,port=443,v4-cidrs=${RUNNER_PUBLIC_IP}/32,description=github-actions-temp-access"

        trap 'echo "=== Закрываем доступ: удаляем временное правило ==="; yc vpc security-group update-rules "$CLEAN_SG_ID" --delete-rule-id=$(yc vpc security-group get "$CLEAN_SG_ID" --format=json | jq -r ".rules[] | select(.description==\"github-actions-temp-access\") | .id" 2>/dev/null || echo "")' EXIT

        yc managed-kubernetes cluster get-credentials --id "$YC_CLUSTER_ID" --external --force --kubeconfig "$HOME/.kube/config"

        REF_NAME="${GITHUB_REF#refs/tags/}"
        CLEAN_REG_ID=$(echo "${{ secrets.YC_REGISTRY_ID }}" | tr -d '\r' | tr -d '\n' | tr -d ' ')
        
        echo "=== Применяем патч к деплойменту в Kubernetes ==="
        kubectl patch deployment diplom-app \
          --namespace=default \
          --type='json' \
          -p="[{\"op\": \"replace\", \"path\": \"/spec/template/spec/containers/0/image\", \"value\": \"cr.yandex/${CLEAN_REG_ID}/diplom-app:${REF_NAME}\"}]"

        kubectl rollout restart deployment/diplom-app --namespace=default
